"use client";
import {useEffect,useRef,useState} from 'react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {blankNumbers,numberFields,numberLabels,profileLabels,applyNumberAction,type NumberAction} from '@/lib/common-numbers';
import type {AppState,Chart,Song,NumberProfile,NumberSettings} from '@/lib/iidx-data';
export function CommonNumberSettings({state,charts,songs,disabled,onApply}:{state:AppState;charts:Chart[];songs:Song[];disabled:boolean;onApply:(action:NumberAction)=>Promise<void>}){
 const [profile,setProfile]=useState<NumberProfile>('SP:1P'),[draft,setDraft]=useState(state.commonNumbers??{}),[align,setAlign]=useState(false),[field,setField]=useState<keyof NumberSettings>('green'),[amount,setAmount]=useState('1'),[pending,setPending]=useState<NumberAction|null>(null),[description,setDescription]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false),[status,setStatus]=useState('');
 const lock=useRef(false);useEffect(()=>setDraft(state.commonNumbers??{}),[state.commonNumbers]);
 const values=draft[profile]??blankNumbers(),stored=state.commonNumbers?.[profile]??blankNumbers(),changed=numberFields.some(key=>values[key]!==stored[key]);
 const prepare=(action:NumberAction)=>{setError('');setStatus('');try{const preview=applyNumberAction(state,charts,songs,action);setDescription(`${profileLabels[profile]}：${action.type==='save'?'共通値を保存'+(action.alignExisting?'し、既存の個別値も共通値にそろえます':'します'):numberLabels[action.field]+`を${action.delta>0?'+':''}${action.delta}調整します`}。個別設定の変更は${preview.changedNotes}件。ソフラン曲・DB未掲載・旧DP表示の不一致による対象外は${preview.excludedNotes}件です。`);setPending(action);}catch(e){setError(e instanceof Error?e.message:'入力値を確認してください。');}};
 const apply=async()=>{if(!pending||disabled||lock.current)return;lock.current=true;setSaving(true);setError('');try{await onApply(pending);setPending(null);setAlign(false);setStatus('緑数字・白数字の設定を保存しました。');}catch(e){setError(e instanceof Error?e.message:'保存できませんでした。');}finally{lock.current=false;setSaving(false);}};
 return <section><h3>共通の緑数字・白数字</h3><p>ソフラン以外の譜面に適用します。曲編集で入力した数値を優先し、空欄の項目には共通値を使います。</p>
 <Tabs value={profile} onValueChange={v=>{setProfile(v as NumberProfile);setError('');setStatus('');}}><TabsList aria-label="共通数値の対象">{(Object.keys(profileLabels) as NumberProfile[]).map(key=><TabsTrigger key={key} value={key} disabled={saving}>{profileLabels[key]}</TabsTrigger>)}</TabsList></Tabs>
 <div className="common-number-fields">{numberFields.map(key=><label className="field-label" key={key}>{numberLabels[key]}<Input aria-label={`共通 ${numberLabels[key]}`} type="number" inputMode="numeric" min={key==='green'?1:0} max={key==='green'?9999:1000} step={1} value={values[key]} placeholder="未設定" disabled={disabled||saving} onChange={e=>setDraft(current=>({...current,[profile]:{...(current[profile]??blankNumbers()),[key]:e.target.value}}))}/></label>)}</div>
 <label className="common-number-align"><Checkbox checked={align} disabled={disabled||saving} onCheckedChange={v=>setAlign(v===true)}/><span>既存の個別値も共通値にそろえる</span></label><p className="common-number-help">チェック時は、この対象の緑数字・白数字の個別指定を共通値へ切り替えます。配置・表示方式・コメントは保持します。</p>
 <button className="save-button" disabled={disabled||saving||(!changed&&!align)} onClick={()=>prepare({type:'save',profile,values,alignExisting:align})}>共通値を保存</button>
 <h4 className="common-number-shift-heading">保存済みの数値を一括微調整</h4><p>共通値とソフラン以外の個別値を同じ量だけ増減します。曲ごとの数値の差は維持します。</p>
 <Select value={field} onValueChange={v=>setField(v as keyof NumberSettings)} disabled={disabled||saving}><SelectTrigger className="choice" aria-label="一括微調整する項目"><SelectValue/></SelectTrigger><SelectContent>{numberFields.map(key=><SelectItem key={key} value={key}>{numberLabels[key]}</SelectItem>)}</SelectContent></Select>
 <div className="common-number-adjust"><button className="secondary-button" disabled={disabled||saving||changed} onClick={()=>prepare({type:'shift',profile,field,delta:-1})}>−1</button><button className="secondary-button" disabled={disabled||saving||changed} onClick={()=>prepare({type:'shift',profile,field,delta:1})}>＋1</button></div>
 <div className="common-number-adjust"><Input aria-label="一括微調整の増減量" type="number" inputMode="text" min={-1000} max={1000} step={1} value={amount} disabled={disabled||saving} onChange={e=>setAmount(e.target.value)}/><button className="secondary-button" disabled={disabled||saving||changed||!amount.trim()} onClick={()=>prepare({type:'shift',profile,field,delta:Number(amount)})}>指定量で調整</button></div>
 {changed&&<p>微調整する前に、変更中の共通値を保存してください。</p>}{disabled&&<p>曲編集の変更を保存してから操作してください。</p>}{error&&!pending&&<p className="transfer-error" role="alert">{error}</p>}{status&&<p role="status">{status}</p>}
 <AlertDialog open={!!pending} onOpenChange={value=>{if(!value&&!lock.current)setPending(null);}}><AlertDialogContent className="save-confirm"><AlertDialogTitle>緑数字・白数字を変更しますか？</AlertDialogTitle><AlertDialogDescription>{description}</AlertDialogDescription>{pending?.type==='save'&&<p>緑 {pending.values.green||'未設定'} ／ SUD+ {pending.values.whiteTop||'未設定'}・LIFT {pending.values.whiteBottom||'未設定'}</p>}{error&&<p className="transfer-error" role="alert">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={saving}>キャンセル</AlertDialogCancel><AlertDialogAction disabled={disabled||saving} onClick={e=>{e.preventDefault();void apply();}}>{saving?'保存中…':'変更する'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </section>;
}
